In [1]:
import requests
import json
from lxml import html

c:\Users\A1ex5\Desktop\CodeFlow\.venv\Lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.4.3)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(

In [ ]:
url = "https://books.toscrape.com/"
headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
    }
res = requests.get(url)
print(res.status_code)
tree = html.fromstring(res.content) # DOM-дерево
products = tree.xpath("//article[@class='product_pod']") # поиск блоков товаров
scraped_data = []
    
    # Извлекаем данные из каждой карточки
for product in products:
        # Название товара (атрибут title ссылки внутри тега <h3>)
    title_list = product.xpath(".//h3/a/@title")
    title = title_list[0] if title_list else "Название не найдено"
        
        # Ссылка на изображение (атрибут src тега <img> внутри блока с классом image_container)
    img_src_list = product.xpath(".//div[@class='image_container']/a/img/@src")
    img_src = img_src_list[0] if img_src_list else "Изображение не найдено"
    img_src = "https://books.toscrape.com/" + img_src.replace("../", "")
        
        # Цена товара (текст внутри тега <p> с классом price_color)
    price_list = product.xpath(".//p[@class='price_color']/text()")
    price = price_list[0] if price_list else "Цена не найдена"
        
       
    product_info = {
            "title": title,
            "image_url": img_src,
            "price": price
        }
    scraped_data.append(product_info)
        
    print(f"{title} - {img_src} - {price}")

    with open("books_data.json", "w", encoding="utf-8") as f:
        json.dump(scraped_data, f, ensure_ascii=False, indent=4)

200
A Light in the Attic - https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg - £51.77
Tipping the Velvet - https://books.toscrape.com/media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg - £53.74
Soumission - https://books.toscrape.com/media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg - £50.10
Sharp Objects - https://books.toscrape.com/media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg - £47.82
Sapiens: A Brief History of Humankind - https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg - £54.23
The Requiem Red - https://books.toscrape.com/media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg - £22.65
The Dirty Little Secrets of Getting Your Dream Job - https://books.toscrape.com/media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg - £33.34
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull - https://books.toscrape.com/media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg - £17.93
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics - https://books.toscrape.com/media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg - £22.60
The Black Maria - https://books.toscrape.com/media/cache/58/46/5846057e28022268153beff6d352b06c.jpg - £52.15
Starving Hearts (Triangular Trade Trilogy, #1) - https://books.toscrape.com/media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg - £13.99
Shakespeare's Sonnets - https://books.toscrape.com/media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg - £20.66
Set Me Free - https://books.toscrape.com/media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg - £17.46
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1) - https://books.toscrape.com/media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg - £52.29
Rip it Up and Start Again - https://books.toscrape.com/media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg - £35.02
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991 - https://books.toscrape.com/media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg - £57.25
Olio - https://books.toscrape.com/media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg - £23.88
Mesaerion: The Best Science Fiction Stories 1800-1849 - https://books.toscrape.com/media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg - £37.59
Libertarianism for Beginners - https://books.toscrape.com/media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg - £51.33
It's Only the Himalayas - https://books.toscrape.com/media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg - £45.17

In [48]:
import pandas as pd

df = pd.DataFrame({'Title':[],'image_url':[], 'price':[]})
for i in range(len(scraped_data)):
    for key in scraped_data[i]:
        df.loc[i, "Title"] = scraped_data[i]['title']
        df.loc[i, "image_url"] = scraped_data[i]['image_url']
        df.loc[i, "price"] = scraped_data[i]['price']

df.to_csv('parsing_book.csv')

C:\Users\A1ex5\AppData\Local\Temp\ipykernel_1148\179572759.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'A Light in the Attic' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[i, "Title"] = scraped_data[i]['title']
C:\Users\A1ex5\AppData\Local\Temp\ipykernel_1148\179572759.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[i, "image_url"] = scraped_data[i]['image_url']
C:\Users\A1ex5\AppData\Local\Temp\ipykernel_1148\179572759.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '£51.77' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[i, "price"] = scraped_data[i]['price']

In [6]:
import requests
from bs4 import BeautifulSoup
import json
url = "https://books.toscrape.com/"
headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
    }

In [9]:

res = requests.get(url, headers=headers)
res.raise_for_status()

soup = BeautifulSoup(res.content, "html.parser")

products = soup.find_all("article", class_="product_pod")

scraped_data = []

for product in products:

    title = product.find("h3").find("a").get("title")

    img_src = product.find("div", class_="image_container").find("img").get("src")

    if img_src.startswith("../"):
        img_src = url + img_src.replace("../", "")

    price = product.find("p", class_="price_color").get_text(strip=True)

    product_info = {
        "title": title,
        "image_url": img_src,
        "price": price
    }

    scraped_data.append(product_info)

    print(f"{title} - {img_src} - {price}")

with open("books_data_bs.json", "w", encoding="utf-8") as f:
    json.dump(scraped_data, f, ensure_ascii=False, indent=4)

A Light in the Attic - media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg - £51.77
Tipping the Velvet - media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg - £53.74
Soumission - media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg - £50.10
Sharp Objects - media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg - £47.82
Sapiens: A Brief History of Humankind - media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg - £54.23
The Requiem Red - media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg - £22.65
The Dirty Little Secrets of Getting Your Dream Job - media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg - £33.34
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull - media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg - £17.93
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics - media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg - £22.60
The Black Maria - media/cache/58/46/5846057e28022268153beff6d352b06c.jpg - £52.15
Starving Hearts (Triangular Trade Trilogy, #1) - media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg - £13.99
Shakespeare's Sonnets - media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg - £20.66
Set Me Free - media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg - £17.46
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1) - media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg - £52.29
Rip it Up and Start Again - media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg - £35.02
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991 - media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg - £57.25
Olio - media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg - £23.88
Mesaerion: The Best Science Fiction Stories 1800-1849 - media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg - £37.59
Libertarianism for Beginners - media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg - £51.33
It's Only the Himalayas - media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg - £45.17

In [23]:
import pandas as pd
import json
with open(r"C:\Users\A1ex5\Downloads\file.json", 'r',encoding='utf-8') as f:
    data_book = json.load(f)
data_book = data_book[0]

In [32]:
df_n8n = pd.DataFrame(columns=["title","image_url","price"]) 
for i in range(len(data_book['title'])):
    df_n8n.loc[i,'title'] = data_book['title'][i]
    df_n8n.loc[i,'image_url'] = url + data_book['image_url'][i]
    df_n8n.loc[i,'price'] = data_book['price'][i]
df_n8n

,title,image_url,price
0,A Light in the Attic,https://books.toscrape.com/media/cache/2c/da/2...,£51.77
1,Tipping the Velvet,https://books.toscrape.com/media/cache/26/0c/2...,£53.74
2,Soumission,https://books.toscrape.com/media/cache/3e/ef/3...,£50.10
3,Sharp Objects,https://books.toscrape.com/media/cache/32/51/3...,£47.82
4,Sapiens: A Brief History of Humankind,https://books.toscrape.com/media/cache/be/a5/b...,£54.23
5,The Requiem Red,https://books.toscrape.com/media/cache/68/33/6...,£22.65
6,The Dirty Little Secrets of Getting Your Dream...,https://books.toscrape.com/media/cache/92/27/9...,£33.34
7,The Coming Woman: A Novel Based on the Life of...,https://books.toscrape.com/media/cache/3d/54/3...,£17.93
8,The Boys in the Boat: Nine Americans and Their...,https://books.toscrape.com/media/cache/66/88/6...,£22.60
9,The Black Maria,https://books.toscrape.com/media/cache/58/46/5...,£52.15
10,"Starving Hearts (Triangular Trade Trilogy, #1)",https://books.toscrape.com/media/cache/be/f4/b...,£13.99
11,Shakespeare's Sonnets,https://books.toscrape.com/media/cache/10/48/1...,£20.66
12,Set Me Free,https://books.toscrape.com/media/cache/5b/88/5...,£17.46
13,Scott Pilgrim's Precious Little Life (Scott Pi...,https://books.toscrape.com/media/cache/94/b1/9...,£52.29
14,Rip it Up and Start Again,https://books.toscrape.com/media/cache/81/c4/8...,£35.02
15,Our Band Could Be Your Life: Scenes from the A...,https://books.toscrape.com/media/cache/54/60/5...,£57.25
16,Olio,https://books.toscrape.com/media/cache/55/33/5...,£23.88
17,Mesaerion: The Best Science Fiction Stories 18...,https://books.toscrape.com/media/cache/09/a3/0...,£37.59
18,Libertarianism for Beginners,https://books.toscrape.com/media/cache/0b/bc/0...,£51.33
19,It's Only the Himalayas,https://books.toscrape.com/media/cache/27/a5/2...,£45.17

# Сравнительная таблица «код vs no-code»

In [33]:
comparison = pd.DataFrame({
    "Критерий": [
        "Трудозатраты",
        "Скорость первоначальной настройки",
        "Объём ручного кода",
        "Использование XPath",
        "Гибкость обработки данных",
        "Наглядность workflow",
        "Удобство изменения логики",
        "Подход для сложного scraping"
    ],
    "Код (Python + lxml + XPath)": [
        "Выше",
        "Средняя",
        "Высокий",
        "Да",
        "Высокая",
        "Средняя",
        "Высокое",
        "Лучше"
    ],
    "No-code (n8n)": [
        "Ниже",
        "Высокая",
        "Минимальный",
        "Нет / зависит от ноды",
        "Средняя",
        "Высокая",
        "Среднее",
        "Хуже при усложнении логики"
    ]
})

comparison

,Критерий,Код (Python + lxml + XPath),No-code (n8n)
0,Трудозатраты,Выше,Ниже
1,Скорость первоначальной настройки,Средняя,Высокая
2,Объём ручного кода,Высокий,Минимальный
3,Использование XPath,Да,Нет / зависит от ноды
4,Гибкость обработки данных,Высокая,Средняя
5,Наглядность workflow,Средняя,Высокая
6,Удобство изменения логики,Высокое,Среднее
7,Подход для сложного scraping,Лучше,Хуже при усложнении логики